CREATE TABLE Produto(
    Nome VARCHAR (50) NOT NULL, 
    DESCRICAO VARCHAR (50) NOT NULL, 
    VLRCOMPRA VARCHAR (10) NOT NULL, 
    VLRVENDA VARCHAR (50) NOT NULL, 
    CATEGORIAS VARCHAR (15) NOT NULL,
    enabled BOOLEAN)