package br.senac.tads.gerenciador.telas;

import br.senac.tads.Servicos.ServicoGerenciador;
import br.senac.tads.Servicos.ServicoGerenciador;
import br.senac.tads.gerenciador.produto.Produto;
import br.senac.tads.gerenciador.produto.Produto;
import java.awt.HeadlessException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class gerenciador extends javax.swing.JFrame {

    /**
     * Creates new form agenda
     */
    public gerenciador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCadastro = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        lbVlrVenda = new javax.swing.JLabel();
        lbVlrCompra = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        btLimpa = new javax.swing.JButton();
        btSalva = new javax.swing.JButton();
        lbNome1 = new javax.swing.JLabel();
        fieldDescricao = new javax.swing.JTextField();
        cbCategorias = new javax.swing.JComboBox<>();
        fieldVlrCompra = new javax.swing.JFormattedTextField();
        fieldVlrVenda = new javax.swing.JFormattedTextField();
        lbTitulo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        lbProdutos = new javax.swing.JLabel();
        btAtualiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbNome.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbNome.setText("Nome:");

        fieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        lbVlrVenda.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbVlrVenda.setText("Valor de Venda:");

        lbVlrCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbVlrCompra.setText("Valor de Compra:");

        lbCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbCategoria.setText("Categorias:");

        btLimpa.setText("Limpar");
        btLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpaActionPerformed(evt);
            }
        });

        btSalva.setText("Salvar");
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });

        lbNome1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbNome1.setText("Descrição:");

        fieldDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescricaoActionPerformed(evt);
            }
        });

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "PS4", "PS3", "Xbox 360", "Xbox One", "PC" }));

        fieldVlrCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldVlrCompraFocusLost(evt);
            }
        });
        fieldVlrCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldVlrCompraActionPerformed(evt);
            }
        });

        fieldVlrVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        fieldVlrVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldVlrVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNome)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome1)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(lbVlrCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldVlrCompra))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(lbVlrVenda)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldVlrVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCategoria)
                                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btLimpa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalva))
                    .addComponent(fieldDescricao))
                .addContainerGap())
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lbNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVlrCompra)
                            .addComponent(lbCategoria)
                            .addComponent(fieldVlrCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVlrVenda)
                            .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldVlrVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLimpa)
                            .addComponent(btSalva))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbTitulo1.setText("Adicionar Jogo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Valor Compra", "Valor Venda", "Categoria"
            }
        ));
        tableProdutos.setEnabled(false);
        jScrollPane1.setViewportView(tableProdutos);

        lbProdutos.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbProdutos.setText("Produtos");

        btAtualiza.setText("Atualizar");
        btAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualiza))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtualiza)
                    .addComponent(lbProdutos))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaActionPerformed
        if (validacaoCampos() == false) {
            JOptionPane.showMessageDialog(this, "Cadastro não preenchido corretamente.");
        }else{
            Produto produto = new Produto();
            try{
                salvaProduto(produto);
            }catch (Exception ex){
                Logger.getLogger(gerenciador.class.getName()).log(Level.SEVERE, null, ex);
            }
        limpaCampos(); 
        }
            
    }//GEN-LAST:event_btSalvaActionPerformed

    private void btLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpaActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btLimpaActionPerformed

    private void btAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaActionPerformed

        DefaultTableModel tab = (DefaultTableModel) tableProdutos.getModel();

        ZerarLista();
        try {
                List<Produto> produto = ServicoGerenciador.listar();
                if (produto == null)
                {
                    JOptionPane.showMessageDialog(this, "Nenhum produto cadastrado.");
                }
                else{
                for (int i = 0; i < produto.size();i++)
                {
                    Produto c = produto.get(i);
                    addlist(tab, c);
                }
                }
            } 
        catch (HeadlessException ex) {
        } catch (Exception ex) {
            Logger.getLogger(gerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_btAtualizaActionPerformed

    private void fieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescricaoActionPerformed

    private void fieldVlrCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldVlrCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldVlrCompraActionPerformed

    private void fieldVlrVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldVlrVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldVlrVendaActionPerformed

    private void fieldVlrCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldVlrCompraFocusLost
    
    }//GEN-LAST:event_fieldVlrCompraFocusLost

    public boolean validacaoCampos() {
        if (fieldNome.getText().equals("")
                || fieldDescricao.getText().equals("")
                || fieldNome.getText().equals("")
                || fieldVlrCompra.getText().equals("")
                || fieldVlrVenda.getText().equals("")
                || cbCategorias.getSelectedItem().equals("Selecione")
                ) {
            return false;
        } else {
            return true;
        }
    }
    
    public void limpaCampos() {
        fieldNome.setText("");
        fieldDescricao.setText("");
        fieldVlrCompra.setText("");
        fieldVlrVenda.setText("");
        cbCategorias.setSelectedItem(1);
        
    }
    
    public void salvaProduto(Produto produto) throws Exception {
        produto.setNome(fieldNome.getText());
        produto.setDescricao(fieldDescricao.getText());
        produto.setValorCompra(fieldVlrCompra.getText());
        produto.setValorVenda(fieldVlrVenda.getText());
        produto.setCategorias((String) cbCategorias.getSelectedItem());
        
        ServicoGerenciador.addProduto(produto);       
        
        JOptionPane.showMessageDialog(this, "Produto salvo com sucesso.");        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new gerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualiza;
    private javax.swing.JButton btLimpa;
    private javax.swing.JButton btSalva;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JTextField fieldDescricao;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JFormattedTextField fieldVlrCompra;
    private javax.swing.JFormattedTextField fieldVlrVenda;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbProdutos;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbVlrCompra;
    private javax.swing.JLabel lbVlrVenda;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JTable tableProdutos;
    // End of variables declaration//GEN-END:variables

    private void ZerarLista() {
    DefaultTableModel tab = (DefaultTableModel) tableProdutos.getModel();
        for (int c = 0; c < tab.getRowCount();) {
            tab.removeRow(0);
        }
    }

    private DefaultTableModel addlist(DefaultTableModel tab, Produto c) {
        tab.addRow(new String[]{c.getNome(),c.getDescricao(), c.getValorCompra(), c.getValorVenda(),
        c.getCategorias()});
        return tab; 
    
    }
}
